import type { Scheme } from './types'

/** Light: Everforest (https://github.com/sainnhe/everforest) hues on a near-white surface with near-black text. */
export const everforestLight: Scheme = {
  primary: '#566B00',
  onPrimary: '#FFFFFF',
  primaryContainer: '#E4EBC4',
  onPrimaryContainer: '#2C3A08',
  secondary: '#1A6E51',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#D7EADF',
  onSecondaryContainer: '#123B2C',
  tertiary: '#A13F88',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#F5DCEA',
  onTertiaryContainer: '#561C47',
  error: '#C0302E',
  errorContainer: '#FBE0D8',
  onErrorContainer: '#761B19',
  success: '#1A6E51',
  warning: '#835A00',
  surface: '#FFFDF7',
  surfaceDim: '#ECE8DA',
  surfaceBright: '#FFFDF7',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FAF7EE',
  surfaceContainer: '#F4F0E3',
  surfaceContainerHigh: '#EDE9DB',
  surfaceContainerHighest: '#E6E2D2',
  onSurface: '#1F2A2F',
  onSurfaceVariant: '#4A5650',
  outline: '#7B887E',
  outlineVariant: '#D8D3C2',
}
